[2.4] CircleCI/Setup fixes (#2924)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,18 +1,6 @@
 version: 2.1
 
 commands:
-  # If this build is from a fork, stop executing the current job and return success.
-  # This is useful to avoid steps that will fail due to missing credentials.
-  early-return-for-forked-pull-requests:
-    steps:
-      - run:
-          name: Early return if this build is from a forked PR
-          command: |
-            if [ -n "$CIRCLE_PR_NUMBER" ]; then
-              echo "Nothing to do for forked PRs, so marking this step successful."
-              circleci step halt
-            fi
-
   early-returns:
     steps:
       - run:
@@ -30,6 +18,18 @@ commands:
               circleci step halt
             fi
 
+  # If this build is from a fork, stop executing the current job and return success.
+  # This is useful to avoid steps that will fail due to missing credentials.
+  early-return-for-forked-pull-requests:
+    steps:
+      - run:
+          name: Early return if this build is from a forked PR
+          command: |
+            if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
+              echo "Nothing to do for forked PRs, so marking this step successful"
+              circleci step halt
+            fi
+
   setup-executor:
     steps:
       - run:
@@ -39,7 +39,7 @@ commands:
             apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
             bash <(curl -fsSL https://raw.githubusercontent.com/docker/docker-install/master/install.sh)
       - setup_remote_docker:
-          version: 20.10.2
+          version: 20.10.14
           docker_layer_caching: true
 
   checkout-all:
@@ -55,24 +55,136 @@ commands:
           name: Setup automation
           command: |
             git submodule update --init deps/readies
+            if [[ $(uname -s) == Darwin ]]; then rm -f /usr/local/bin/python3; fi
             ./deps/readies/bin/getpy3
+      - run:
+          name: Setup automation (2)
+          shell: /bin/bash -l -eo pipefail
+          command: |
+            export HOMEBREW_NO_AUTO_UPDATE=1
+            ./deps/readies/bin/getpy2
+            ./deps/readies/bin/getaws
+            ls -l /usr/local/bin/python* || true
+            echo "python3: $(command -v python3)"
+            python3 --version
+            python3 -m pip list
 
-  persist-artifacts:
-    steps:
-      - persist_to_workspace:
-          root: bin/artifacts
-          paths:
-            - 'snapshots/*.zip'
-            - 'snapshots/*.tgz'
-            - '*.zip'
-            - '*.tgz'
-
-  setup-prerequisits:
+  install-prerequisites:
+    parameters:
+      redis_version:
+        type: string
+        default: "6"
+      getredis_params:
+        type: string
+        default: ""
+      benchmarks:
+        type: string
+        default: "no"
     steps:
       - setup-automation
       - run:
-          name: Install prerequisites
-          command: ./sbin/system-setup.py
+          name: Install remote benchmark python dependencies
+          command: |
+            if [[ "<<parameters.benchmarks>>" == "yes" ]]; then
+              python3 -m pip install -r ./tests/benchmarks/requirements.txt
+            fi
+      - run:
+          name: System setup
+          shell: /bin/bash -l -eo pipefail
+          command: |
+            ./sbin/system-setup.py
+            python3 -m pip list
+      - run:
+          name: Install Redis
+          shell: /bin/bash -l -eo pipefail
+          command: |
+            python3 ./deps/readies/bin/getredis -v '<<parameters.redis_version>>' --force <<parameters.getredis_params>>
+            redis-server --version
+      - run:
+          name: Install remote benchmark tool dependencies
+          command: |
+            if [[ "<<parameters.benchmarks>>" == "yes" ]]; then
+              VERSION=0.14.8 ./deps/readies/bin/getterraform
+            fi
+
+  save-tests-logs:
+    steps:
+      - run:
+          name: Cleanup test log dir
+          command: |
+            rm -f tests/flow/logs/*.{aof,rdb}
+            rm -f tests/tck/logs/*.{aof,rdb}
+          when: always
+      - store_artifacts:
+          path: tests/flow/logs
+      - store_artifacts:
+          path: tests/tck/logs
+
+  persist-artifacts:
+    steps:
+      - early-return-for-forked-pull-requests
+      - run:
+          name: List artifacts
+          command: |
+            cd bin/artifacts
+            du -ah --apparent-size *
+      - persist_to_workspace:
+          root: bin/
+          paths:
+            - artifacts/*.zip
+            - artifacts/*.tgz
+            - artifacts/*.tar
+
+  platform-build-steps:
+    parameters:
+      platform:
+        type: string
+    steps:
+      - early-returns
+      - setup-executor
+      - checkout-all
+      - setup-automation
+      - run:
+          name: Build for platform
+          shell: /bin/bash -l -eo pipefail
+          command: |
+            cd build/docker
+            make build DOCKER_SUFFIX=".<<parameters.platform>>" OSNICK=<<parameters.platform>> PACK=1 TEST=1 VERBOSE=1
+      - early-return-for-forked-pull-requests
+      - run:
+          name: Build for platform (docker publish)
+          command: |
+            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
+            cd build/docker
+            make build DOCKER_SUFFIX=".<<parameters.platform>>" OSNICK=<<parameters.platform>> PACK=1 TEST=1 VERBOSE=1 PUBLISH=1 DOCKERWRAPPER_EXTRA_VARS="DOCKER_PUSH_ONLY=1"
+      - persist-artifacts
+
+  vm-build-platforms-steps:
+    parameters:
+      platform:
+        type: string
+    steps:
+      - early-returns
+      - checkout-all
+      - setup-automation
+      - run:
+          name: Install Docker
+          shell: /bin/bash -l -eo pipefail
+          command: ./deps/readies/bin/getdocker
+      - run:
+          name: Build for platform
+          command: |
+            cd build/docker
+            make build DOCKER_SUFFIX=".<<parameters.platform>>" OSNICK=<<parameters.platform>> PACK=1 TEST=1 VERBOSE=1
+          no_output_timeout: 30m
+      - early-return-for-forked-pull-requests
+      - run:
+          name: Publish container
+          command: |
+            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
+            cd build/docker
+            make build DOCKER_SUFFIX=".<<parameters.platform>>" OSNICK=<<parameters.platform>> PACK=1 TEST=1 VERBOSE=1 PUBLISH=1 DOCKERWRAPPER_EXTRA_VARS="DOCKER_PUSH_ONLY=1"
+      - persist-artifacts
 
   benchmark-automation:
     parameters:
@@ -94,92 +206,49 @@ commands:
           name: Run CI benchmarks on aws
           no_output_timeout: 30m # given we use very large datasets we need this timeout
           command: |
-              cd ./tests/benchmarks
-              export AWS_ACCESS_KEY_ID=$PERFORMANCE_EC2_ACCESS_KEY
-              export AWS_SECRET_ACCESS_KEY=$PERFORMANCE_EC2_SECRET_KEY
-              export AWS_DEFAULT_REGION=$PERFORMANCE_EC2_REGION
-              export EC2_PRIVATE_PEM=$PERFORMANCE_EC2_PRIVATE_PEM
+            cd tests/benchmarks
+            export AWS_ACCESS_KEY_ID=$PERFORMANCE_EC2_ACCESS_KEY
+            export AWS_SECRET_ACCESS_KEY=$PERFORMANCE_EC2_SECRET_KEY
+            export AWS_DEFAULT_REGION=$PERFORMANCE_EC2_REGION
+            export EC2_PRIVATE_PEM=$PERFORMANCE_EC2_PRIVATE_PEM
 
-              redisbench-admin run-remote \
-                --module_path << parameters.module_path >> \
-                --github_actor << parameters.github_actor >> \
-                --github_repo $CIRCLE_PROJECT_REPONAME \
-                --github_org $CIRCLE_PROJECT_USERNAME \
-                --github_sha $CIRCLE_SHA1 \
-                --github_branch $CIRCLE_BRANCH \
-                --upload_results_s3 \
-                --triggering_env circleci \
-                --required-module graph \
-                --push_results_redistimeseries
-
-  platform-build-steps:
-    parameters:
-      platform:
-        type: string
-    steps:
-      - early-returns
-      - setup-executor
-      - checkout-all
-      - setup-automation
-      - run:
-          name: Build for platform (docker build)
-          command: |
-            make -C build/docker build DOCKER_SUFFIX=".<<parameters.platform>>" OSNICK=<<parameters.platform>> PACK=1 TEST=1 VERBOSE=1
-      - early-return-for-forked-pull-requests
-      - run:
-          name: Build for platform (docker publish)
-          command: |
-            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
-            make -C build/docker build DOCKER_SUFFIX=".<<parameters.platform>>" OSNICK=<<parameters.platform>> PACK=1 TEST=1 VERBOSE=1 PUBLISH=1 DOCKERWRAPPER_EXTRA_VARS="DOCKER_PUSH_ONLY=1"
-      - persist-artifacts
-
-  vm-build-platforms-steps:
-    parameters:
-      platform:
-        type: string
-    steps:
-      - early-returns
-      - checkout-all
-      - setup-automation
-      - run:
-          name: Install Docker
-          command: bash <(curl -fsSL https://raw.githubusercontent.com/docker/docker-install/master/install.sh)
-      - run:
-          name: Build for platform
-          command: |
-            make -C build/docker build DOCKER_SUFFIX=".<<parameters.platform>>" OSNICK=<<parameters.platform>> PACK=1 TEST=1 VERBOSE=1
-          no_output_timeout: 30m
-      - early-return-for-forked-pull-requests
-      - run:
-          name: Build for platform (publish)
-          command: |
-            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
-            make -C build/docker build DOCKER_SUFFIX=".<<parameters.platform>>" OSNICK=<<parameters.platform>> PACK=1 TEST=1 VERBOSE=1 PUBLISH=1 DOCKERWRAPPER_EXTRA_VARS="DOCKER_PUSH_ONLY=1"
-      - persist-artifacts
+            redisbench-admin run-remote \
+              --module_path << parameters.module_path >> \
+              --github_actor << parameters.github_actor >> \
+              --github_repo $CIRCLE_PROJECT_REPONAME \
+              --github_org $CIRCLE_PROJECT_USERNAME \
+              --github_sha $CIRCLE_SHA1 \
+              --github_branch $CIRCLE_BRANCH \
+              --upload_results_s3 \
+              --triggering_env circleci \
+              --required-module graph \
+              --push_results_redistimeseries
 
 #----------------------------------------------------------------------------------------------------------------------------------
 
 jobs:
   build:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-bionic
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
       - early-returns
       - checkout-all
-      - setup-prerequisits
+      - install-prerequisites
       - restore_cache:
           keys:
             - v1-GraphBLAS-build-{{ checksum "deps/GraphBLAS/README.md" }}
       - run:
           name: Build
-          command: bash -l -c "make all package"
+          shell: /bin/bash -l -eo pipefail
+          command: make all package
       - save_cache:
           paths:
             - deps/GraphBLAS/build
           key: v1-GraphBLAS-build-{{ checksum "deps/GraphBLAS/README.md" }}
       - run:
           name: Test
-          command: bash -l -c "make test"
+          shell: /bin/bash -l -eo pipefail
+          command: make test
       - early-return-for-forked-pull-requests
       - run:
           name: Persist Artifact for CI benchmarks
@@ -194,31 +263,33 @@ jobs:
 
   coverage:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-bionic
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
       - early-returns
       - checkout-all
-      - setup-prerequisits
+      - install-prerequisites
       - restore_cache:
           keys:
             - v1-GraphBLAS-build-{{ checksum "deps/GraphBLAS/README.md" }}
       - run:
           name: Build for coverage
-          command: bash -l -c "make COV=1"
+          shell: /bin/bash -l -eo pipefail
+          command: make COV=1
       - run:
           name: Test with coverage
+          shell: /bin/bash -l -eo pipefail
           command: |
-            bash -l -c "make test COV=1"
-            bash -l -c "make cov-upload"
-          no_output_timeout: 30m
+            make test COV=1
+            make cov-upload
+          no_output_timeout: 45m
 
   build_memcheck:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-bionic
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
       - early-returns
       - checkout-all
-      - setup-prerequisits
+      - install-prerequisites
       - restore_cache:
           keys:
             - v1-GraphBLAS-build-{{ checksum "deps/GraphBLAS/README.md" }}
@@ -226,11 +297,12 @@ jobs:
           at: /workspace
       - run:
           name: Test for memory leaks
+          shell: /bin/bash -l -eo pipefail
           command: |
             # Replace the default Redis server with one linked to libc malloc rather than jemalloc
             python3 ./deps/readies/bin/getredis --force --valgrind
             # Re-run the test suite, failing if definite memory leaks have been introduced
-            bash -l -c "make memcheck"
+            make memcheck
           # Allow RediSearch global destructors
           environment:
             RS_GLOBAL_DTORS: 1
@@ -246,25 +318,28 @@ jobs:
 
   build_macos:
     macos:
-      xcode: 12.4.0
+      xcode: 12.5.1
+    resource_class: macos.x86.medium.gen2
     steps:
       - early-returns
       - checkout-all
-      - setup-prerequisits
+      - install-prerequisites
       - restore_cache:
           keys:
             - GraphBLAS-mac-{{ checksum "deps/GraphBLAS/README.md" }}
       - run:
           name: Build
+          shell: /bin/bash -l -eo pipefail
           command: |
-            bash -l -c "make all package"
+            make all package
       - save_cache:
           paths:
             - deps/GraphBLAS/build
           key: GraphBLAS-mac-{{ checksum "deps/GraphBLAS/README.md" }}
       - run:
           name: Test
-          command: bash -l -c "make test"
+          shell: /bin/bash -l -eo pipefail
+          command: make test
       - store_artifacts:
           path: ~/project/tests/flow/logs
       - persist-artifacts
@@ -281,7 +356,7 @@ jobs:
 
   deploy_branch:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-bionic
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
       - attach_workspace:
           at: artifacts
@@ -295,7 +370,7 @@ jobs:
 
   deploy_release:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-bionic
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
       - attach_workspace:
           at: artifacts
@@ -309,8 +384,10 @@ jobs:
 
   release_automation:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-buster
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
+      - early-returns
+      - early-return-for-forked-pull-requests
       - checkout
       - setup-automation
       - run:
@@ -319,8 +396,10 @@ jobs:
 
   nightly_automation:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-buster
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
+      - early-returns
+      - early-return-for-forked-pull-requests
       - checkout
       - setup-automation
       - run:
@@ -329,22 +408,22 @@ jobs:
 
   performance_ci_automation_not_integ:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-bionic
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
       - early-returns
       - checkout
-      - setup-prerequisits
+      - install-prerequisites
       - attach_workspace:
           at: /workspace
       - benchmark-automation
 
   performance_ci_automation:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-bionic
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
       - early-returns
       - checkout
-      - setup-prerequisits
+      - install-prerequisites
       - attach_workspace:
           at: /workspace
       - run:
@@ -355,11 +434,11 @@ jobs:
 
   nightly_performance_automation:
     docker:
-      - image: redisfab/rmbuilder:6.2.5-x64-bionic
+      - image: redisfab/rmbuilder:6.2.7-x64-bullseye
     steps:
       - early-returns
       - checkout-all
-      - setup-prerequisits
+      - install-prerequisites
       - attach_workspace:
           at: /workspace
       - run:
@@ -372,6 +451,13 @@ jobs:
 #----------------------------------------------------------------------------------------------------------------------------------
 
 on-any-branch: &on-any-branch
+  filters:
+    branches:
+      only: /.*/
+    tags:
+      only: /.*/
+
+always: &always
   filters:
     branches:
       only: /.*/
@@ -402,6 +488,15 @@ on-integ-branch: &on-integ-branch
     tags:
       ignore: /.*/
 
+on-integ-branch-cron: &on-integ-branch-cron
+  filters:
+    branches:
+      only:
+        - master
+        - /^\d+\.\d+.*$/
+        - /^feature-.*$/
+        - /^perf-.*$/
+
 not-on-integ-branch: &not-on-integ-branch
   filters:
     branches:
@@ -429,9 +524,15 @@ on-integ-and-version-tags: &on-integ-and-version-tags
     tags:
       only: /^v[0-9].*/
 
-context: &context
-  context:
-    - common
+on-perf-tags: &on-perf-tags
+  filters:
+    branches:
+      only:
+        - master
+        - /^\d+\.\d+.*$/
+        - /^perf-.*$/
+    tags:
+      only: /^v[0-9].*/
 
 #----------------------------------------------------------------------------------------------------------------------------------
 
@@ -440,47 +541,48 @@ workflows:
   build_and_package:
     jobs:
       - build:
-          <<: *context
+          context: common
           <<: *not-on-integ-branch
       - coverage:
-          <<: *context
-          <<: *on-any-branch
+          context: common
+          <<: *always
       - build_memcheck:
-          <<: *context
+          context: common
           <<: *on-any-branch
       - build_macos:
-          <<: *context
-          <<: *on-integ-and-version-tags
+          context: common
+          #<<: *on-integ-and-version-tags
+          <<: *never
       - platform_build:
-          <<: *context
+          context: common
           <<: *on-integ-and-version-tags
           matrix:
             parameters:
-              platform: [bionic, xenial, centos7, centos8]
+              platform: [bionic, xenial, centos7, rocky8]
       - deploy_branch:
-          <<: *context
+          context: common
           <<: *on-integ-branch
           requires:
             - platform_build
-            - build_macos
+            #- build_macos
       - release_automation:
-          <<: *context
+          context: common
           <<: *on-version-tags
           requires:
             - deploy_release
       - deploy_release:
-          <<: *context
+          context: common
           <<: *on-version-tags
           requires:
             - platform_build
-            - build_macos
+            #- build_macos
       - performance_ci_automation_not_integ:
-          <<: *context
+          context: common
           <<: *not-on-integ-branch
           requires:
             - build
       - performance_ci_automation:
-          <<: *context
+          context: common
           <<: *on-integ-and-version-tags
           requires:
             - platform_build
@@ -494,4 +596,4 @@ workflows:
               only: master
     jobs:
       - nightly_performance_automation:
-          <<: *context
+          context: common
